### PR TITLE
Several fixes and changes to the introduction

### PR DESCRIPTION
**Pull request by jonasmalacofilho**
Summary:
- Changed certain concept translations:
  - inlined fields: campos expandidos em linha (instead of "campos
    alinhados")
  - pattern matching: casamento de padrões (instead of "localização de
    padrões"), used in Wikipedia but still a bad name; perhaps
    something more in the lines of "extração de padrões" would be more
    appropriate
- Fixed typos
- Other minor changes

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
I changed certain concept translations, but I'm not totally sure about the result:
- inlined fields: campos expandidos em linha (instead of "campos alinhados")
- pattern matching: casamento de padrões (instead of "localização de padrões"), used in Wikipedia but still a bad name; perhaps something more in the lines of "extração de padrões" would be more appropriate

@aszasz , what's your take on this?

**Comment by aszasz** [comment]
Thank you for the fixes and the encouragement. I am merging the request.

I think that at these early stages, this is the best way to work. In fact you shall merge yourself what you see fit, and if we see something that was changed back and forth, then we discuss. The bellow is just to explain myself.

I saw a few non-important things that I think were better before, but I am sure it is matter of taste, for example: 
- Last line: "Haxe 3 switch was flipped" = "chave do Haxe 3" or "a chave para o Haxe 3"?, where I considered  "interruptor" or "botão" and "foi acionada" or "foi ligada" )
- Line 32: "brief overview" = "breve visão geral" ou "visão geral mas abrevidada" ? 

Then I saw two things that need still to be fixed as changing became incomplete:
- Line 38: your correction should have deleted "que" instead of "o" when rephrasing.
- Line 32: second case, still think it need commas "visão geral, mas abreviada, ..."

As for the concepts, I really don't know what is best: when translating the corresponding session one can feel it better and go with whatever:
-  the problem with "campos expandidos em linha" is that gets too long in the phrases, even it conceives the concept better; I don't remember having given attention to inline fields in the text, but to inlined functions, which I felt "funções alinhadas" did a nice job.
- for "pattern matching" I considered both "casamento" and "extração", and even "encaixe" and "coincidência", but localization worked well on the session I guess "casamento" is what conveys the idea better, even it sounds uncomfortable at the begining of the reading.

I still comment that I had removed the word section in line 32 because the rereference is to a chapter, but I agree I shall keep it as the original, because it is a translation (at least at this point) and not a version.

**Comment by jonasmalacofilho** [comment]
1. I think either "a chava do Haxe 3 foi acionada" or "a chave para o Haxe foi virada" are appropriate, but you're correct that it is somewhat a matter of taste
2. "breve visão geral" is closer to the original meaning (obviously), but it's almost paradoxical in Portuguese, since it uses three words to briefly (without prepositons) describe brevity; that's why, in the moment, I thought it would be best to expand it to "visão geral mas abreviada".
3. I don't think the "os" is necessary, but the change from "façam" to "fazerem" was incorrect; I'll fix that briefly.
4. I'll add the commas, although we still might decide to change the expression back (or to something else)
5. I really dislike "alinhadas" for two reasons:
   - It doesn't convey at all that the original field is expanded to its definition in every place where it's used, very much like in a textual substitution
   - Alignment is another important concept in computation, and even though it's totally unrelated, it comes to mind (and causes confusion) since it also applies to structure (and object) fields
6. I think "casamento" sounds wrong, but it is semantically correct in the sense of _logical_ pairing of things; in fact, I think that best translation to English of "casamento de padrões" would indeed be "pattern matching".

P.S. We can also add annotations directly to the commit diff, instead of meonting the lines in a comment.

**Comment by jonasmalacofilho** [comment]
I added the word "session" before the self-reference to "Introdução" because in the resulting PDF the reference only results in the number 1.

**Pull request merged**
